/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: moyicat (https://sketchfab.com/moyicat)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/room-02-magica-voxel-42de6218d891419f8ad9e623777e003e
title: Room 02 / Magica Voxel
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

export default function Model(props) {
  const roomRef = useRef(); 
  console.log(roomRef.current)
  const { nodes, materials } = useGLTF("./room_02__magica_voxel/Room.gltf");
  useFrame((state, delta) => {
    roomRef.current.rotation.y = THREE.MathUtils.lerp(
      roomRef.current.rotation.y,
      (Math.PI / 180) * 610,
      delta
    );
    roomRef.current.scale.x = THREE.MathUtils.lerp(
      roomRef.current.scale.x,
      0.2,
      delta
    );
    roomRef.current.scale.y = THREE.MathUtils.lerp(
      roomRef.current.scale.y,
      0.2,
      delta
    );
    roomRef.current.scale.z = THREE.MathUtils.lerp(
      roomRef.current.scale.z,
      0.2,
      delta
    );
  });
  return (
    <group castShadow ref={roomRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-16, -16, 0]}>
          <mesh
            geometry={nodes.Object_2.geometry}
            material={materials["Scene_-_Root"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./room_02__magica_voxel/Room.gltf");
