/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: moyicat (https://sketchfab.com/moyicat)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/room-02-magica-voxel-42de6218d891419f8ad9e623777e003e
title: Room 02 / Magica Voxel
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d";
import { MotionConfig } from "framer-motion";
import { useFrame } from "@react-three/fiber";
export default function Model(props) {
  const roomRef = useRef();
  const { nodes, materials } = useGLTF("/room_02__magica_voxel/Room.gltf");
  useFrame((state, delta) => {
    roomRef.current.rotation.y += 0.01;
  });
  return (
    <MotionConfig
      transition={{
        duration: 2,
        type: "tween",
      }}
    >
      <motion.group
        animate={{ scale: 0.2, rotateY: (Math.PI / 180) * 610 }}
        ref={roomRef}
        {...props}
        dispose={null}
      >
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group position={[-16, -16, 0]}>
            <mesh
              geometry={nodes.Object_2.geometry}
              material={materials["Scene_-_Root"]}
            />
          </group>
        </group>
      </motion.group>
    </MotionConfig>
  );
}

useGLTF.preload("/room_02__magica_voxel/Room.gltf");
